name: Dev CI
on:
  push:
    branches:
      - dev
  workflow_dispatch:
env:
  IMAGE: sxiaohao/valuation
  TAG: ${{ github.sha }}
jobs:
  build:
    strategy:
      matrix:
        go: [1.16]
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Unit Test
        run: |
          go test ./...
  deploy:
    strategy:
      matrix:
        go: [1.16]
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Image Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.IMAGE }}:${{ env.TAG }}

      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker stop valuation && docker rm valuation
            docker image prune -af
            docker pull ${{ env.IMAGE }}:${{ env.TAG }}
            docker run -d --name valuation -p ${{ secrets.SERVER_PORT }}:8000 --restart=always -e MYSQL_SOURCE -e REDIS_PASSWORD -e HOST -e AMQP_URI ${{ env.IMAGE }}:${{ env.TAG }}
